# Generated by Django 4.2 on 2023-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='true', max_length=200, null='true')),
                ('price', models.FloatField(null='true')),
                ('category', models.CharField(blank='true', choices=[('smartphone', 'Smart phone'), ('earphone', 'Ear phone'), ('powerbank', 'PowerBank')], max_length=20)),
                ('warranty', models.IntegerField(choices=[(1, '1 year'), (2, '2 years'), (3, '3 years')])),
            ],
        ),
    ]
