# Generated by Django 4.2 on 2023-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(choices=[(0, 'No warranty'), (1, '1 year'), (2, '2 years'), (3, '3 years')]),
        ),
    ]
